### ISSUE TITLE
[Bug] /coins unstack will delete coins if there is not enough empty inventory space to unstack

### ISSUE THREAD

**Issue by Luke616** [flametaichou/OrdinaryCoins#3]
The "/coins unstack" command will erase any coins which there is no space for in the inventory. 

For example, if silver coins are set to be worth 64 copper, unstacking 30 silver coins when there are only 19 free slots in the inventory will cause 10 silver worth of coins to be erased.

Thanks!

Using:
Ordinary Coins 1.3.4
Minecraft 1.12.2
Forge 2768

**Comment by flametaichou** [comment]
Fixed in v1.4. Thank you for bugreport!
