### ISSUE TITLE
Crash with Certain Configs (?)

### ISSUE THREAD

**Issue by dodgycoffee** [flametaichou/OrdinaryCoins#6]
I'm not sure if this is a bug or something else. I tweaked some configs on the mod recently and made zombies/spiders drop 0 coins. It seems like based on the crash error I'm getting it didn't like that?

I'm pasting the full report as well. It mentions an entity from MatterOverdrive as well. But I made no changes to that mod and everything has been working fine for the better part of a month. This crash started occuring yesterday on our server. And then on a fresh new SP world, same crash. I'm not sure the other mod should be affecting it at all because the drops only work with vanilla mobs.

[crash-2019-03-25_12.41.41-server.txt](https://github.com/OrdinaryMinecraft/OrdinaryCoins/files/3004509/crash-2019-03-25_12.41.41-server.txt)

**Update:**
We tried re-enabling the coins for zombies and spiders. Changed it from 0 to 1 and suddenly crashes are gone. Seems like the config can't handle 0 as a drop value for some reason.

**Comment by flametaichou** [comment]
Fixed in version 1.5
