### ISSUE TITLE
Mod Support for Other Mobs?

### ISSUE THREAD

**Issue by Azuriuz** [flametaichou/OrdinaryCoins#7]
I would love to be able to use this mod on my server in the near future, if that's alright with you! (I didn't see your policy on including it in a modpack)

I would like to put in a request for mod support. 
This mod is by far the best currency from mob drops mod that I have seen, and I would love to be able to make the coins drop from more than just vanilla mobs. For example Grimoire of Gaia, Mowzie's Mobs, maybe even Ice and Fire? 
I'm sure you are very busy, but if it's possible to add mod support then please let me know?

**Comment by TheSexyYeti** [comment]
I second this. It would be nice to have a whitelist in the configs that allows mod pack creators the ability  to add mobs from other mods to the list mobs that will drop coins Along with what coins they'll drop and how many of those coins they drop.

**Comment by flametaichou** [comment]
Starting from version 1.5 any mob can be configured in the ordinarycoins.cfg
